version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:///app/db/development.sqlite3
